### ISSUE TITLE
Missing bridge between setup.ts GitHub secrets and Kubernetes placeholders

### ISSUE THREAD

**Issue by willgriffin** [willgriffin/company-as-code#162]
## Problem

The template has a fundamental architectural gap where `setup.ts` stores secrets in GitHub repository secrets, but there's no mechanism to sync these secrets into Kubernetes, leaving placeholder values unreplaced.

## Discovered In

This issue was found while deploying [happyvertical/iac#5](https://github.com/happyvertical/iac/issues/5) where multiple placeholder values weren't being replaced, causing deployment failures.

### Current Two-Phase Process (Broken)
1. **Phase 1** (`setup.ts`): 
   - ✅ Creates S3 bucket for Terraform state
   - ✅ Stores secrets in **GitHub repository secrets**
   - ✅ Sets up CI/CD environment variables

2. **Phase 2** (Kubernetes deployment):
   - ❌ Manifests contain `placeholder-will-be-updated` values
   - ❌ Secret generation job only creates random passwords
   - ❌ No mechanism to pull from GitHub repository secrets
   - ❌ External Secrets configured but missing GitHub backend

### The Gap
**Missing**: GitHub Repository Secrets → Kubernetes Secrets bridge

## Impact on Template Users

Every deployment requires manual intervention to replace placeholder values:
- DigitalOcean API tokens for DNS operations
- AWS credentials for state storage
- SES SMTP credentials for email
- Admin user credentials

This breaks the "one-click deployment" promise of the template.

### Secrets Stored in GitHub
```typescript
// setup.ts lines 650-660
const secrets: Record<string, string> = {
  PROJECT_NAME: this.config.project.name,
  DIGITALOCEAN_TOKEN: process.env.DIGITALOCEAN_TOKEN || '',
  TERRAFORM_STATE_BUCKET: s3Config.bucketName,
  TERRAFORM_STATE_REGION: s3Config.region,
  AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID || '',
  AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY || '',
  ADMIN_EMAIL: this.config.project.email,
  // ... stored in GitHub repository secrets
};
```

### Kubernetes Manifests with Placeholders
```yaml
# manifests/system/digitalocean-secrets/credentials.yaml
stringData:
  digitalocean-token: "placeholder-will-be-updated"  # ❌ Never replaced
  aws-access-key-id: "placeholder-will-be-updated"   # ❌ Never replaced
  admin-username: "{{SETUP_REPO_EMAIL}}"             # ❌ Never replaced
```

### 1. Add GitHub Secrets as External Secret Backend

Create `manifests/system/external-secrets/github-secret-store.yaml`:
```yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: github-secret-store
  namespace: external-secrets
spec:
  provider:
    github:
      auth:
        token:
          secretRef:
            name: github-token
            key: token
      owner: "{{GITHUB_OWNER}}"
      repo: "{{GITHUB_REPO}}"
```

### 2. Update External Secrets to Pull from GitHub

Modify external secrets to use GitHub as source instead of local credentials:
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: digitalocean-secrets
spec:
  secretStoreRef:
    kind: SecretStore
    name: github-secret-store
  data:
  - secretKey: digitalocean-token
    remoteRef:
      key: DIGITALOCEAN_TOKEN
```

### 3. Enhance setup.ts

Add GitHub Personal Access Token creation and storage:
```typescript
// In setup.ts, add GitHub token handling
private async setupGitHubSecrets(): Promise<void> {
  // Create GitHub token for External Secrets access
  // Store in kubernetes secret for External Secrets to use
  // Update all External Secret configurations
}
```

### 4. Update Documentation

- Clarify the two-phase setup process
- Document GitHub token requirements
- Add troubleshooting for placeholder values

### Phase 1: GitHub Backend Support
1. Add GitHub secret store configuration
2. Create GitHub token setup in `setup.ts`
3. Test with DigitalOcean token as proof of concept

### Phase 2: Full Migration
1. Migrate all External Secrets to use GitHub backend
2. Remove placeholder-based credentials secret
3. Update secret generation job scope

### Phase 3: Documentation & Testing
1. Update README with new setup flow
2. Add troubleshooting guide
3. Test full deployment flow

## Breaking Changes

This will require:
- Additional GitHub Personal Access Token with `repo` scope
- External Secrets Operator GitHub provider support
- Updates to existing deployments

## Acceptance Criteria

- [ ] `setup.ts` completion results in fully functional deployment
- [ ] No placeholder values remain after setup
- [ ] External Secrets pulls from GitHub repository secrets
- [ ] Documentation reflects new setup process
- [ ] Existing template users have migration path

## Related Issues

- [happyvertical/iac#5](https://github.com/happyvertical/iac/issues/5) - Discovery issue
- [happyvertical/iac#2](https://github.com/happyvertical/iac/issues/2) - DigitalOcean token symptom

## Priority

**Critical** - This affects the core value proposition of the template (one-click deployment) and impacts every user.
